import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo App by Saad',
  description: 'Generated by my self',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
      <h1>Awesome TODO App</h1>
      {children}
      
      
      </body>
    </html>
  )
}
